log_dir: "../exp/3dmatch_eval"
threads: 4

run_ransac: true
rte_thresh: 0.3
rre_thresh: 15.0
mode: "test"

pcd_root: "../exp/3dmatch_data/testing_lmdb"
gt_root: "../exp/3dmatch_data/testing_info"

test_scene_names:
  - "7-scenes-redkitchen"
  - "sun3d-home_at-home_at_scan1_2013_jan_1"
  - "sun3d-home_md-home_md_scan9_2012_sep_30"
  - "sun3d-hotel_uc-scan3"
  - "sun3d-hotel_umd-maryland_hotel1"
  - "sun3d-hotel_umd-maryland_hotel3"
  - "sun3d-mit_76_studyroom-76-1studyroom2"
  - "sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika"

test_scene_abbr_names:
  - "Kitchen"
  - "Home_1"
  - "Home_2"
  - "Hotel_1"
  - "Hotel_2"
  - "Hotel_3"
  - "Study"
  - "MIT_Lab"
